### ISSUE TITLE
Keep static bzip2 for Python build

### ISSUE THREAD

**Issue by xhochy** [conda-forge/bzip2-feedstock#14]
When/if bzip2 removes the static library it will be necessary to update the python recipes as they statically link to libbz2 to avoid [bus errors when the bzip2 is updated by conda](https://github.com/AnacondaRecipes/python-feedstock/blob/b3606929c4a5d23517635388413b4e86ed9c9345/recipe/build.sh#L60-L64)

_Originally posted by @jjhelmus in https://github.com/conda-forge/conda-forge.github.io/issues/1095#issuecomment-656188267_

**Comment by xhochy** [comment]
@jjhelmus I guess this means that we should add an output here to also build `libbz2.a` and use that in Python? I guess otherwise we will run into the bus error ahain.

**Comment by jjhelmus** [comment]
Yes, Python really needs the static library. A `bzip2-static` or `libbz2-static` output would be great.

**Comment by isuruf** [comment]
On Ubuntu, `lib-dynload/_bz2.*.so` is linked to the shared library. Can we do the same? Or am I missing something here?

**Comment by jjhelmus** [comment]
We can try dynamically linking the `_bz2` module.  

My recollection is that this caused issues if the past when conda updates the `bzip2` packages because Python was using libbz2.so for unpacking a .tar.bz2 file which is unlinked during the transaction.  This may not be the case anymore, it would be worthwhile to test this.

**Comment by isuruf** [comment]
Ah, this must be before conda started using `libarchive`

**Comment by jjhelmus** [comment]
Yes, this was before the move to `conda-package-handling` (cph) which uses libarchive, although even cph falls back the `bz2` module (via tarfile) when libarchive is not available.

**Comment by jjhelmus** [comment]
`_libarchive_static_for_cph-feedstock` needs a [static version of libbz2 as well as a number of other libraries](https://github.com/conda-forge/_libarchive_static_for_cph-feedstock/blob/master/recipe/build.sh#L34-L65).

**Comment by isuruf** [comment]
None of the pkgs mentioned here needs a static library anymore.
