### ISSUE TITLE
bzip2 website offline

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/bzip2-feedstock#4]
This was raised by someone else raised via a different channel. Apparently the bzip2 website is parked. As we still need access to the source for future rebuilds there is some question of what we should do. The downloads still appear to be available from the Wayback Machine (downloaded and checksumed archive attached), but that's not something we can count on forever. Would suggest sticking them in a release tag on this repo. Thoughts?

archive: [bzip2-1.0.6.tar.gz](https://github.com/conda-forge/bzip2-feedstock/files/2298027/bzip2-1.0.6.tar.gz)

ref: https://web.archive.org/web/20180624184835/http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz

cc @conda-forge/core

**Comment by CJ-Wright** [comment]
There is also this? https://github.com/enthought/bzip2-1.0.6 Maybe we can ask them to make a "tag"?

**Comment by CJ-Wright** [comment]
Or maybe fork it, tag it, and use that as the source?

**Comment by jakirkham** [comment]
Have attached the archive in the OP of this issue because apparently GitHub allows that. 😄

**Comment by CJ-Wright** [comment]
Impressive!

**Comment by jjhelmus** [comment]
I used the link from https://fossies.org/linux/misc/bzip2-1.0.6.tar.gz/ for #5.  This seemed to be a reasonable source but I'm open to other suggestions.
